import {
  ArrowDown,
  ArrowsDownUp,
  ArrowSquareOut,
  ArrowUp,
  Bell,
  Broom,
  CalendarBlank,
  CheckSquare,
  Coins,
  CurrencyDollar,
  Eye,
  EyeSlash,
  House,
  Kanban,
  List,
  MagnifyingGlass,
  Pen,
  Plugs,
  PlugsConnected,
  Plus,
  Receipt,
  SignOut,
  SortAscending,
  SortDescending,
  SquaresFour,
  Timer,
  UserPlus,
  Users,
} from 'phosphor-svelte';
import type { Component } from 'svelte';
import type { IconContextProps } from 'phosphor-svelte';

export type PhosphorIcon = Component<IconContextProps['values']>;

export const Ph = {
  Bell: Bell as unknown as PhosphorIcon,
  House: House as unknown as PhosphorIcon,
  Users: Users as unknown as PhosphorIcon,
  UserPlus: UserPlus as unknown as PhosphorIcon,
  List: List as unknown as PhosphorIcon,
  MagnifyingGlass: MagnifyingGlass as unknown as PhosphorIcon,
  SignOut: SignOut as unknown as PhosphorIcon,
  Receipt: Receipt as unknown as PhosphorIcon,
  Kanban: Kanban as unknown as PhosphorIcon,
  ArrowUp: ArrowUp as unknown as PhosphorIcon,
  ArrowDown: ArrowDown as unknown as PhosphorIcon,
  ArrowSquareOut: ArrowSquareOut as unknown as PhosphorIcon,
  ArrowsDownUp: ArrowsDownUp as unknown as PhosphorIcon,
  CurrencyDollar: CurrencyDollar as unknown as PhosphorIcon,
  Coins: Coins as unknown as PhosphorIcon,
  CheckSquare: CheckSquare as unknown as PhosphorIcon,
  Timer: Timer as unknown as PhosphorIcon,
  CalendarBlank: CalendarBlank as unknown as PhosphorIcon,
  Plugs: Plugs as unknown as PhosphorIcon,
  PlugsConnected: PlugsConnected as unknown as PhosphorIcon,
  SquaresFour: SquaresFour as unknown as PhosphorIcon,
  SortAscending: SortAscending as unknown as PhosphorIcon,
  SortDescending: SortDescending as unknown as PhosphorIcon,
  Broom: Broom as unknown as PhosphorIcon,
  Pen: Pen as unknown as PhosphorIcon,
  Plus: Plus as unknown as PhosphorIcon,
  Eye: Eye as unknown as PhosphorIcon,
  EyeSlash: EyeSlash as unknown as PhosphorIcon,
};
