export {
  Bell as PhBell,
  House as PhHouse,
  Users as PhUsers,
  List as PhList,
  MagnifyingGlass as PhMagnifyingGlass,
  SignOut as PhSignOut,
  Receipt as PhReceipt,
  Kanban as PhKanban,
  ArrowUp as PhArrowUp,
  ArrowDown as PhArrowDown,
  CurrencyDollar as PhCurrencyDollar,
  Coins as PhCoins,
  CheckSquare as PhCheckSquare,
  Timer as PhTimer,
  CalendarBlank as PhCalendarBlank,
} from 'phosphor-svelte';
